name = "xugou-backend"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

# 添加定时触发器，每分钟执行一次监控检查
[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "xugou_tz_db" #替换成你自己的数据库名字
database_id = "33020cda-fd3c-4bb2-8cb5-569c95c65af6" #替换成你自己的数据库id

[version_metadata]
binding = "CF_VERSION_METADATA"
